name: Version Bump
on:
    push:
        branches:
            - main

concurrency:
    group: bump-${{ github.ref }}
    cancel-in-progress: false

jobs:
    bump:
        if: ${{ github.actor != 'hog-management[bot]' }}
        runs-on: ubuntu-latest
        permissions:
            actions: none
            checks: none
            contents: write
            issues: none
            pull-requests: none
        steps:
            - name: Create GitHub App token
              id: app-token
              uses: actions/create-github-app-token@v1
              with:
                  app-id: ${{ vars.HOG_MANAGEMENT_APP_ID }}
                  private-key: ${{ secrets.APP_KEY }}

            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ steps.app-token.outputs.token }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Analyze Commit
              id: commit-lint
              run: npm run actions:lint-commit
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_ENV: actions

            - name: Configure Git
              run: |
                  git config user.name "hog-management[bot]"
                  git config user.email "hog-management[bot]@users.noreply.github.com"

            - name: Bump Version
              if: steps.commit-lint.outputs.bump-type != 'none' && github.actor != 'hog-management[bot]'
              run: npm version ${{ steps.commit-lint.outputs.bump-type }}

            - name: Push Changes
              if: steps.commit-lint.outputs.bump-type != 'none'
              run: |
                  git pull --rebase
                  git push
                  git push --tags
