name: PR Title Lint
on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

concurrency:
    group: lint-pr-title-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint-pr-title:
        runs-on: ubuntu-latest
        permissions:
            actions: none
            checks: write
            contents: read
            issues: none
            pull-requests: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install limited dependencies
              run: npm install --no-save --no-audit --fund=false @actions/core @actions/github

            - name: Lint PR Title
              run: npm run actions:lint-pr
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  ENVIRONMENT: ${{ vars.NODE_ENV }}
