name: PR Checks

on:
    pull_request:
        paths-ignore:
            - "src"
            - "tools"
            - "package.json"
            - "package-lock.json"
    push:
        branches:
            - "main"
        paths-ignore:
            - "src"
            - "tools"
            - "package.json"
            - "package-lock.json"

concurrency:
    group: pr-checks-${{ github.ref }}
    cancel-in-progress: false

jobs:
    pr-checks:
        runs-on: ubuntu-latest
        permissions:
            actions: none
            checks: write
            contents: read
            issues: none
            pull-requests: none

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - name: Create the output directory
              run: mkdir -p temp/lint

            - name: Install dependencies
              run: npm ci

            - name: Compilation Check
              run: npm run tscheck

            - name: Run ESLint with JSON report
              run: npm run lint:report
              continue-on-error: true

            - name: Annotate ESLint results
              uses: ataylorme/eslint-annotate-action@21a1ba0738d8b732639999029c4ff40b6e121bb4
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  report-json: temp/lint/eslint_report.json
                  fail-on-error: true
                  fail-on-warning: false

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: linting-reports
                  path: ./temp/lint
                  if-no-files-found: error
                  compression-level: 9
